### ISSUE TITLE
Is new mechanism guaranteed behaviour?

### ISSUE THREAD

**Issue by risicle** [Invicton-Labs/terraform-null-assertion#1]
~Not really an "issue" (great start), but...~

~It's neat you found a way to trigger an error without the dummy external call.~

~The only thing I worry about with the new mechanism is "is this guaranteed terraform behaviour?". It seems to me that all that would have to change is terraform switching to a lazier form of evaluation and all of a sudden a `local` which is referenced by no `resource`, `data` or `output` could just be ignored.~

Wait, I'm an idiot and wasn't seeing `outputs.tf` :facepalm: . Ignore me.

**Comment by KyleKotowick** [comment]
Since it doesn't seem there's an issue here, I'm just going to close this :)
